apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
      - name: engine
        image: docker.io/harish9959/rag-engine:v7
        imagePullPolicy: Always
        env:
        - name: QDRANT_HOST
          value: "qdrant"
        - name: QDRANT_PORT_NUM
          value: "6333"
        - name: OLLAMA_HOST
          value: "http://ollama:11434"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
