apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        env:
        - name: QDRANT__SERVICE__HTTP_ADDRESS
          value: "0.0.0.0" # This is the magic line
        ports:
        - containerPort: 6333 # API port
        - containerPort: 6334 # gRPC port
